### ISSUE TITLE
How to use it ?

### ISSUE THREAD

**Issue by Bakarseck** [Dar-rius/goproject#2]
Hello, please can you explain more how to use this gproject add push-swap .                                                                                                                              [22:16:35]
Config File "path" Not Found in "[]"
2023/12/11 22:19:26 error: Config File "path" Not Found in "[]"

**Comment by Dar-rius** [comment]
Hello, first of all thank you for trying the application.

Regarding the use of the application as written in the [readme](https://github.com/Dar-rius/gproject#readme) the goal is to move very fast in a folder from the terminal, to do that you must first that the application can know the path of your folder for that you type the following command: 
```bash
$ gproject add <project_name> <project_path>
```
After executing this command, the path to your folder will be saved in a json nome path.json.

To check that the path to your folder has been saved, type the following command: 
```bash
$ gproject ls 
```
This command will display a list of folders and their paths stored in a path.json file.

Once the path to your folder has been saved, you can move directly to your folder by typing the following command: 
```bash
$ gproject go <project_name>
```
You'll arrive in your folder

**Comment by Bakarseck** [comment]
Thanks
